### ISSUE TITLE
Sugestão: remover a propriedade "tipo"

### ISSUE THREAD

**Issue by relesbao** [carteiro/ceps#12]
Após analisar algumas bases de dados de ceps, não encontrei nenhuma que forneça o "tipo", mesmo que seja possível extrair o tipo do logradouro, acredito que depender disso para preencher o campo não seja tão confiável.

Talvez fornecer apenas o logradouro e deixar esse problema de resolver o tipo para as aplicações.

Exemplo:
https://viacep.com.br/ws/93022750/json/

**Comment by wandersonwhcr** [comment]
Será que não seria interessante, no nosso caso, informar sempre o tipo do logradouro? No arquivo `tests/config.json` eu adicionei todos os tipos que encontrei no formulário de busca dos Correios.

Acho que é o caso de padronizarmos isso...

**Comment by relesbao** [comment]
Concordo.
