### ISSUE TITLE
Upgrade???

### ISSUE THREAD

**Issue by PauloBoaventura** [carteiro/ceps#29]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by wandersonwhcr** [comment]
Olá @PauloBoaventura, tudo bem?

Este projeto ainda está em desenvolvimento.

Como podes ver, nossa base de dados está muito no início. Estamos pensando em como fazer com que os dados sejam preenchidos pelos próprios desenvolvedores, não utilizando as bases já encontradas na Internet, para não violar as diferentes licenças de _software_ proprietário.

Tu podes contribuir, criando novos arquivos JSON, com base nos arquivos encontrados no diretório `/data` deste projeto.

Abraços.

**Comment by wandersonwhcr** [comment]
Por favor, leia o arquivo `README.md` do projeto para mais detalhes.

https://github.com/carteiro/ceps/blob/master/README.md

**Comment by PauloBoaventura** [comment]
Olá @wandersonwhcr compreendo... 
Estou tendo problemas para fazer implementação na plataforma Magento 1.9 ou 2.1...
Preciso que efetivamente tenha um calculo e que este, seja adicionado ao pedido para que o mesmo seja finalizado...
Poderia me ajudar neste caso, com qualquer orientação a respeito?

**Comment by wandersonwhcr** [comment]
@PauloBoaventura infelizmente, este não é o foco do projeto.
